# Enables the Quobyte CSI plugin if set to true.
# Please configure the CSI plugin in charts/quobyte-csi/values.yaml
csi_enabled: false

# Enables automatic Quobyte client deployments if set to true.
# Must be enabled and configured when using the CSI plugin.
# Please configure in charts/quobyte-client/values.yaml
client_enabled: false 

# Enables the provisioning of Quobyte services if set to true.
# Please consult the readme for requirements for running
# the Quobyte services on Kubernetes.
# Please configure in charts/quobyte-core/values.yaml
core_enabled: true

quobyte-csi:
  quobyte:
    quobyteUser: amFuLXF1b2J5dGU= 
    quobytePassword: dGVzdC4xMjM0 
