# Decides if csi framework and quobyte driver should be deployed using this chart
csi_enabled: true

# decides if quobyte clients should be deployed using this chart
client_enabled: true 

# decides if quobyte core services (metadata, registry, dataservice, quobyte-api, web-console
# shall be deployed using this chart.
core_enabled: true
