---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quobyte-data
spec:
  selector:
    matchLabels:
      app: quobyte-data # has to match .spec.template.metadata.labels
  serviceName: "quobyte-data"
  replicas: {{ .Values.quobyte.replicas }} # by default is 4 
  template:
    metadata:
      labels:
        app: quobyte-data # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
      - name: quobyte-data-pre 
        image: {{ .Values.quobyte.image }}
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: QUOBYTE_DATA_PORT 
            value: "7863"
          - name: QUOBYTE_META_PORT
            value: "7862"
          - name: QUOBYTE_REG_PORT 
            value: "7861"
          - name: QUOBYTE_API_PORT
            value: "7860" 
          - name: QUOBYTE_SERVICE
            value: data
          - name: CLOUD_INSTALL
            value: "1" 
          - name: CLUSTER_NS
            value: {{ .Release.Namespace }}
          - name: LIMIT_OPEN_FILES
            value: "{{ .Values.quobyte.maxopenfiles }}"
          - name: LIMIT_MAX_PROCESSES
            value: "{{ .Values.quobyte.maxprocs }}"
        volumeMounts:
          - name: config
            mountPath: /etc/quobyte
          {{- range .Values.quobyte.datadisks }}
          - name: {{ .name }}
            mountPath: {{ .mountpoint }}
          {{- end }}
        command:
              - /bin/sh 
              - -xc
              - |
                touch /etc/quobyte/$QUOBYTE_SERVICE.cfg
                echo test.device_dir=/var/lib/quobyte/devices >> /etc/quobyte/data.cfg
                for i in $(basename $(ls -d /var/lib/quobyte/devices/data*))
                do
                  if [ ! -e /var/lib/quobyte/devices/${i}/QUOBYTE_DEV_SETUP ];then
                    /usr/bin/qmkdev -d -t DATA /var/lib/quobyte/devices/${i}
                  fi
                done
                attempts=0
                while [[ $attempts < 60 ]]
                do
                  cnt=0
                  for i in 0 1 2 3
                  do
                    r=$(curl -s -o /dev/null -I -w "%{http_code}" http://quobyte-reg-${i}.quobyte.${CLUSTER_NS}.svc.cluster.local:7871/)
                    if [ $r -eq 200 ];then
                      ((cnt++))
                    fi
                  done
                  if [ $cnt -eq 4 ];then
                    exit 0
                  fi
                  ((attempts++))
                  sleep 1
                done
      containers:
      - name: quobyte-data
        image: {{ .Values.quobyte.image }}
        imagePullPolicy: Always
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: QUOBYTE_DATA_PORT 
            value: "7863"
          - name: QUOBYTE_META_PORT
            value: "7862"
          - name: QUOBYTE_REG_PORT 
            value: "7861"
          - name: QUOBYTE_API_PORT
            value: "7860" 
          - name: QUOBYTE_SERVICE
            value: data
          - name: CLOUD_INSTALL
            value: "1" 
          - name: CLUSTER_NS
            value: {{ .Release.Namespace }}
          - name: QUOBYTE_REGISTRY
            value: quobyte.{{ .Release.Namespace }}.svc.cluster.local
          - name: LIMIT_OPEN_FILES
            value: "{{ .Values.quobyte.maxopenfiles }}"
          - name: LIMIT_MAX_PROCESSES
            value: "{{ .Values.quobyte.maxprocs }}"
        ports:
        - containerPort: 7863
          name: quobyte-data
        volumeMounts:
          - name: config
            mountPath: /etc/quobyte
          {{- range .Values.quobyte.datadisks }}
          - name: {{ .name }}
            mountPath: {{ .mountpoint }}
          {{- end }}
      nodeSelector:
           cloud.google.com/gke-nodepool: {{ .Values.nodepoolname }}
      affinity:
        podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - quobyte
              topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi
{{- range .Values.quobyte.datadisks }}
  - metadata:
      name: {{ .name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "faster"
      resources:
        requests:
          storage: {{ .size }}
{{- end }}

