{{- if .Values.externaldns.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externaldns.name }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.externaldns.name }}
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.externaldns.name }}-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.externaldns.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.externaldns.name }}
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.externaldns.name }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.externaldns.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.externaldns.name }}
    spec:
      serviceAccountName: external-dns
      containers:
      - name: {{ .Values.externaldns.name }}
        image: {{ .Values.externaldns.image }}
        args:
        - --source=service
        - --domain-filter={{ .Values.externaldns.domainfilter }}
        - --provider={{ .Values.externaldns.provider }}
        - --registry=txt
        - --log-level={{ .Values.externaldns.loglevel }}
      nodeSelector:
           cloud.google.com/gke-nodepool: {{ .Values.nodepoolname }}
{{- end }}

