---
# this is a work around to enable pod name resolution
# It should not work in theory, but we will see
apiVersion: v1
kind: Service
metadata:
  name: quobyte
  labels:
    app: quobyte
spec:
  clusterIP: "None"
  ports:
  - port: 7861
    name: "quobyte"
    targetPort: 7861
  selector:
    app: quobyte-reg

