---
# this is a work around to enable pod name resolution
# It should not work in theory, but we will see
apiVersion: v1
kind: Service
metadata:
  name: quobyte
  labels:
    app: quobyte
spec:
  clusterIP: "None"
  ports:
  - port: 7865
    name: "quobyte"
    protocol: "TCP"
  selector:
    app: quobyte-reg

